global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "prometheus:9090" ]

  - job_name: "node_exporter"
    static_configs:
      - targets: [ "node-exporter:9100" ]

  - job_name: "kafka_exporter"
    static_configs:
      - targets: [ "kafka-exporter:9308" ]

  - job_name: 'kafka-broker'
    static_configs:
      - targets: [ 'kafka:9101' ]

  - job_name: 'spark-master'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'spark-master:8080' ]

  - job_name: 'spark-workers'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'worker01:8081', 'worker02:8081' ]

  - job_name: 'hadoop-namenode'
    metrics_path: /jmx
    params:
      qry: [ 'Hadoop:service=NameNode,name=NameNodeInfo' ]
    static_configs:
      - targets: [ 'namenode:9870' ]

  - job_name: 'hadoop-datanode'
    metrics_path: /jmx
    params:
      qry: [ 'Hadoop:service=DataNode,name=DataNodeInfo' ]
    static_configs:
      - targets: [ 'datanode:9864' ]

  - job_name: 'elasticsearch'
    metrics_path: /_prometheus/metrics
    static_configs:
      - targets: [ 'elasticsearch:9200' ]

  - job_name: 'logstash'
    metrics_path: /_node/stats
    static_configs:
      - targets: [ 'logstash:9600' ]